models:
  gpt-4.1:
    model_url: "https://api.openai.com/v1/chat/completions"
    model_name: "gpt-4.1"
    api_key: "${OPENAI_API_KEY}"
  gpt-4.1-nano:
    model_url: "https://api.openai.com/v1/chat/completions"
    model_name: "gpt-4.1-nano"
    api_key: "${OPENAI_API_KEY}"